#define     FAMICON_VERSION     (1)
#include    "src/anim.h"
#include    "lib/micromages.h"
#include    "lib/neslib.h"
#include    "lib/globals.h"
#include    "src/i18n.c"
#include    "src/ia.c"
#include    "src/draw.c"
#include    "src/game.c"
#include    "src/anim.c"