; This file for the FamiTone2 library and was generated by FamiStudio

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-27
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $70 ;instrument 00 (Instrument 1)
	.word @env1, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c8,$7f,$00,$00
@song0ch0:
	.byte $fb, $01, $80
@song0ref4:
	.byte $1a, $8d, $00, $8b, $22, $8d, $00, $a9, $22, $8d, $00, $8b, $1a, $8d, $00, $a9, $22, $8d, $00, $a9
	.byte $ff, $14
	.word @song0ref4
@song0ref27:
	.byte $24, $8d, $00, $8b, $2c, $8d, $00, $a9, $2c, $8d, $00, $8b, $24, $8d, $00, $a9, $2c, $8d, $00, $a9
	.byte $ff, $14
	.word @song0ref27
@song0ch0loop:
	.byte $80
@song0ref52:
	.byte $22, $8d, $00, $8b, $28, $8d, $00, $a9, $28, $8d, $00, $8b, $22, $8d, $00, $a9, $28, $8d, $00, $a9
	.byte $ff, $14
	.word @song0ref52
@song0ref75:
	.byte $2c, $8d, $00, $8b, $32, $8d, $00, $a9, $32, $8d, $00, $8b, $2c, $8d, $00, $a9, $32, $8d, $00, $a9
	.byte $ff, $14
	.word @song0ref75
@song0ref98:
	.byte $30, $8d, $00, $8b, $36, $8d, $00, $a9, $36, $8d, $00, $8b, $30, $8d, $00, $a9, $36, $8d, $00, $a9
	.byte $ff, $14
	.word @song0ref75
	.byte $ff, $14
	.word @song0ref52
	.byte $ff, $14
	.word @song0ref98
	.byte $fd
	.word @song0ch0loop
@song0ch1:
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5
@song0ch1loop:
	.byte $80, $32, $f9, $f3, $32, $f5, $36, $b9, $3a, $b9, $3c, $f9, $f3, $3c, $f9, $f3, $40, $f9, $f3, $3c, $f9, $f3, $32, $f9
	.byte $f3, $40, $b9, $3c, $b9, $3a, $b9, $36, $b9, $fd
	.word @song0ch1loop
@song0ch2:
	.byte $f9, $f5, $80
@song0ref178:
	.byte $33, $00, $97, $33, $00, $97, $33, $00, $97, $33, $00, $97
	.byte $ff, $0c
	.word @song0ref178
@song0ref193:
	.byte $3d, $00, $97, $3d, $00, $97, $3d, $00, $97, $3d, $00, $97
	.byte $ff, $0c
	.word @song0ref193
	.byte $ff, $0c
	.word @song0ref193
	.byte $ff, $0c
	.word @song0ref193
@song0ch2loop:
	.byte $80
@song0ref216:
	.byte $33, $00, $97, $33, $00, $95, $3b, $00, $97, $3b, $00, $99
	.byte $ff, $0c
	.word @song0ref178
	.byte $ff, $0c
	.word @song0ref216
	.byte $ff, $0c
	.word @song0ref178
@song0ref237:
	.byte $3d, $00, $97, $3d, $00, $97, $45, $00, $97, $45, $00, $97
	.byte $ff, $0c
	.word @song0ref193
	.byte $ff, $0c
	.word @song0ref237
	.byte $ff, $0c
	.word @song0ref237
@song0ref258:
	.byte $41, $00, $97, $41, $00, $97, $49, $00, $97, $49, $00, $97
	.byte $ff, $0c
	.word @song0ref258
	.byte $ff, $0c
	.word @song0ref237
	.byte $ff, $0c
	.word @song0ref193
@song0ref279:
	.byte $33, $00, $97, $33, $00, $97, $3b, $00, $97, $3b, $00, $97
	.byte $ff, $0c
	.word @song0ref279
	.byte $ff, $0c
	.word @song0ref258
	.byte $ff, $0c
	.word @song0ref258
	.byte $fd
	.word @song0ch2loop
@song0ch3:
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5
@song0ch3loop:
	.byte $80
@song0ref313:
	.byte $49, $00, $97, $49, $00, $97, $4b, $00, $97, $4b, $00, $97, $49, $00, $b5, $49, $00, $b5
	.byte $ff, $12
	.word @song0ref313
@song0ref334:
	.byte $49
@song0ref335:
	.byte $00, $97, $49, $00, $97, $4b, $00, $97, $4b, $00, $b5, $49, $00, $97, $4b, $00, $b5
	.byte $ff, $12
	.word @song0ref334
	.byte $4b
	.byte $ff, $11
	.word @song0ref335
	.byte $ff, $12
	.word @song0ref334
	.byte $ff, $0e
	.word @song0ref313
	.byte $97, $49, $00, $97, $4b, $00, $97, $4b, $00, $97, $4b
	.byte $ff, $11
	.word @song0ref335
	.byte $fd
	.word @song0ch3loop
@song0ch4:
	.byte $f9, $f5, $f9, $f5, $f9, $f5, $f9, $f5
@song0ch4loop:
	.byte $ff, $14
	.word @song0ref4
	.byte $ff, $14
	.word @song0ref4
	.byte $ff, $14
	.word @song0ref27
	.byte $ff, $14
	.word @song0ref27
@song0ref403:
	.byte $28, $8d, $00, $8b, $30, $8d, $00, $a9, $30, $8d, $00, $8b, $28, $8d, $00, $a9, $30, $8d, $00, $a9
	.byte $ff, $14
	.word @song0ref27
	.byte $ff, $14
	.word @song0ref4
	.byte $ff, $14
	.word @song0ref403
	.byte $fd
	.word @song0ch4loop